name: monster_must_die
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flame: ^1.0.0-releasecandidate.14
  provider: 6.0.0
  socket_io_client: ^1.0.1
  numberpicker: ^2.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:
  assets:
    - assets/images/
    - assets/images/Enemy/
    - assets/images/Enemy/archer/
    - assets/images/Enemy/cyclop/
    - assets/images/Enemy/dog/
    - assets/images/Enemy/eye/
    - assets/images/Enemy/gargoyle/
    - assets/images/Enemy/ghost/
    - assets/images/Enemy/zombie/
    - assets/images/Unit/archer/
    - assets/images/Unit/balista/
    - assets/images/Unit/berserker/
    - assets/images/Unit/cavalrer/
    - assets/images/Unit/dragon/
    - assets/images/Unit/marshall/
    - assets/images/Unit/spear/
    - assets/images/Unit/wizard/

  uses-material-design: true

