name: main
description: 
version: 1.0.0

environment:
  sdk: '>=2.15.0-42.0.dev <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  
dependencies: 
  socket_io: ^1.0.1

#If you can't run the server or install a new package,
# do : dart pub get

#You can generate a doc : dartdoc
#https://dart.dev/tools/dartdoc

#Generate a build : dart compile exe bin/main.dart